# Generated by Django 4.2.30 on 2026-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionconfig',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
