# Generated by Django 4.2.30 on 2026-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sectionconfig_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='issued_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
